# Container settings
ARG containerSource=ubuntu
ARG containerVersion=plucky

FROM $containerSource:$containerVersion

# Packages
ARG packageManager=apt
ARG packages="build-essential g++ cmake pkg-config libsdl3-dev git"

RUN --mount=type=cache,target=/var/cache \
    $packageManager update -y
RUN $packageManager install -y $packages

# User settings
ARG username=ubuntu


# Et cetera

USER $username